# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 562d524a0ac32c86e1351b4f86142ddecffd2f7ed825ee021e6b500c5b9827950bf6d097e7fc32222bef45f1661f6a9a5f05e85561faa7ef4a8d0b9d824be419

test:
  secret_key_base: b23873bbc3631500f6d75a85916de8dd1b5734d782115ab410255dc12661872a949d47307884f45fe961a112ea8719c3b621bb066ffdaa58f787b21130695d8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
